// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/go-faster/errors"
)

func (s ArticlesGetOKApplicationJSON) Validate() error {
	alias := ([]Article)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}

func (s ArticlesSearchPostOKApplicationJSON) Validate() error {
	alias := ([]Article)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}
