// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	ArticlesGetOperation        OperationName = "ArticlesGet"
	ArticlesIDDeleteOperation   OperationName = "ArticlesIDDelete"
	ArticlesIDGetOperation      OperationName = "ArticlesIDGet"
	ArticlesIDPutOperation      OperationName = "ArticlesIDPut"
	ArticlesPostOperation       OperationName = "ArticlesPost"
	ArticlesSearchPostOperation OperationName = "ArticlesSearchPost"
)
