// Code generated by ogen, DO NOT EDIT.
package api

type ArticlesGetRes interface {
	articlesGetRes()
}

type ArticlesIDDeleteRes interface {
	articlesIDDeleteRes()
}

type ArticlesIDGetRes interface {
	articlesIDGetRes()
}

type ArticlesIDPutRes interface {
	articlesIDPutRes()
}

type ArticlesPostRes interface {
	articlesPostRes()
}

type ArticlesSearchPostRes interface {
	articlesSearchPostRes()
}
