// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ArticlesGet implements GET /articles operation.
//
// Получение списка статей.
//
// GET /articles
func (UnimplementedHandler) ArticlesGet(ctx context.Context, params ArticlesGetParams) (r ArticlesGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ArticlesIDDelete implements DELETE /articles/{id} operation.
//
// Удаление статьи.
//
// DELETE /articles/{id}
func (UnimplementedHandler) ArticlesIDDelete(ctx context.Context, params ArticlesIDDeleteParams) (r ArticlesIDDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ArticlesIDGet implements GET /articles/{id} operation.
//
// Получение статьи по ID.
//
// GET /articles/{id}
func (UnimplementedHandler) ArticlesIDGet(ctx context.Context, params ArticlesIDGetParams) (r ArticlesIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ArticlesIDPut implements PUT /articles/{id} operation.
//
// Обновление статьи.
//
// PUT /articles/{id}
func (UnimplementedHandler) ArticlesIDPut(ctx context.Context, req *ArticleUpdate, params ArticlesIDPutParams) (r ArticlesIDPutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ArticlesPost implements POST /articles operation.
//
// Создание новой статьи.
//
// POST /articles
func (UnimplementedHandler) ArticlesPost(ctx context.Context, req *ArticleCreate) (r ArticlesPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ArticlesSearchPost implements POST /articles/search operation.
//
// Поиск статей по смыслу текста через SearchService.
//
// POST /articles/search
func (UnimplementedHandler) ArticlesSearchPost(ctx context.Context, req *SearchRequest) (r ArticlesSearchPostRes, _ error) {
	return r, ht.ErrNotImplemented
}
