openapi: 3.0.0
info:
  title: Article Service API
  version: 1.0.0
  description: |
    Сервис для CRUD операций со статьями.

paths:
  /articles:
    post:
      summary: Создание новой статьи
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ArticleCreate'
      responses:
        '201':
          description: Статья успешно создана
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

    get:
      summary: Получение списка статей
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 3
        - name: tags
          in: query
          schema:
            type: array
            items:
              type: string
            description: Фильтр по тегам
      responses:
        '200':
          description: Список статей
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Article'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /articles/{id}:
    get:
      summary: Получение статьи по ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Статья найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    put:
      summary: Обновление статьи
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ArticleUpdate'
      responses:
        '200':
          description: Статья обновлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    delete:
      summary: Удаление статьи
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Статья удалена
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    ArticleCreate:
      type: object
      required:
        - title
        - content
        - author
      properties:
        title:
          type: string
        content:
          type: string
        author:
          type: string
        tags:
          type: array
          items:
            type: string

    ArticleUpdate:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        author:
          type: string
        tags:
          type: array
          items:
            type: string

    Article:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        content:
          type: string
        author:
          type: string
        updated_at:
          type: string
          format: date-time
        tags:
          type: array
          items:
            type: string

  responses:
    BadRequest:
      description: Некорректный запрос
    NotFound:
      description: Статья не найдена
    InternalServerError:
      description: Внутренняя ошибка сервера